[package]
name = "compiler-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "compiler"
path = "src/compiler_cli.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
